/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

const CryptoAddress = IDL.Record({
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'amount' : IDL.Text,
});

const PaymentRequest = IDL.Record({
  'nickname' : IDL.Text,
  'currency' : IDL.Text,
  'txHash' : IDL.Text,
  'status' : IDL.Text,
  'submittedAt' : IDL.Int,
});

const PdfEntry = IDL.Record({
  'id' : IDL.Text,
  'blockId' : IDL.Text,
  'filename' : IDL.Text,
  'base64Data' : IDL.Text,
  'uploadedAt' : IDL.Int,
});

const TxCheckResult = IDL.Record({
  'amount' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Text,
  'toAddress' : IDL.Text,
  'addressMatch' : IDL.Bool,
  'eurAmount' : IDL.Opt(IDL.Float64),
  'errorMsg' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
      ['query'],
    ),
  'incrementVisitorCount' : IDL.Func([], [], []),
  'recordHeartbeat' : IDL.Func([IDL.Text], [], []),
  'getActiveVisitorCount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
      ['query'],
    ),
  'getMusterschreibenCount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
      [],
    ),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCryptoAddress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'getCryptoAddresses' : IDL.Func(
      [],
      [IDL.Vec(CryptoAddress)],
      ['query'],
    ),
  'submitPaymentProof' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'getMyPaymentStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentRequest)],
      ['query'],
    ),
  'getAllPaymentRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PaymentRequest), 'error' : IDL.Text })],
      ['query'],
    ),
  'approvePayment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'rejectPayment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'hasMusterschreibenAccess' : IDL.Func(
      [IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'grantMusterschreibenAccess' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'revokeMusterschreibenAccess' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'verifyBTCTransaction' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'confirmed' : IDL.Null, 'pending' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'checkTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : TxCheckResult, 'error' : IDL.Text })],
      [],
    ),
  'addPdfEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
      [],
    ),
  'deletePdfEntry' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
      [],
    ),
  'getPdfEntriesByBlock' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PdfEntry)],
      [],
    ),
  'getAllPdfEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PdfEntry), 'error' : IDL.Text })],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'method' : IDL.Text, 'blob_hash' : IDL.Text })],
      [],
    ),
});

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CryptoAddress = IDL.Record({
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'amount' : IDL.Text,
  });
  const PaymentRequest = IDL.Record({
    'nickname' : IDL.Text,
    'currency' : IDL.Text,
    'txHash' : IDL.Text,
    'status' : IDL.Text,
    'submittedAt' : IDL.Int,
  });
  const PdfEntry = IDL.Record({
    'id' : IDL.Text,
    'blockId' : IDL.Text,
    'filename' : IDL.Text,
    'base64Data' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const TxCheckResult = IDL.Record({
    'amount' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Text,
    'toAddress' : IDL.Text,
    'addressMatch' : IDL.Bool,
    'eurAmount' : IDL.Opt(IDL.Float64),
    'errorMsg' : IDL.Opt(IDL.Text),
  });
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
        ['query'],
      ),
    'incrementVisitorCount' : IDL.Func([], [], []),
    'recordHeartbeat' : IDL.Func([IDL.Text], [], []),
    'getActiveVisitorCount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
        ['query'],
      ),
    'getMusterschreibenCount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
        [],
      ),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCryptoAddress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'getCryptoAddresses' : IDL.Func(
        [],
        [IDL.Vec(CryptoAddress)],
        ['query'],
      ),
    'submitPaymentProof' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'getMyPaymentStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentRequest)],
        ['query'],
      ),
    'getAllPaymentRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PaymentRequest), 'error' : IDL.Text })],
        ['query'],
      ),
    'approvePayment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'rejectPayment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'hasMusterschreibenAccess' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'grantMusterschreibenAccess' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'revokeMusterschreibenAccess' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'verifyBTCTransaction' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'confirmed' : IDL.Null, 'pending' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'checkTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : TxCheckResult, 'error' : IDL.Text })],
        [],
      ),
    'addPdfEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text })],
        [],
      ),
    'deletePdfEntry' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'error' : IDL.Text })],
        [],
      ),
    'getPdfEntriesByBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PdfEntry)],
        [],
      ),
    'getAllPdfEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PdfEntry), 'error' : IDL.Text })],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'method' : IDL.Text, 'blob_hash' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
