/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface CryptoAddress { 'currency' : string; 'address' : string; 'amount' : string; }
export interface PaymentRequestRecord { 'nickname' : string; 'currency' : string; 'txHash' : string; 'status' : string; 'submittedAt' : bigint; }
export interface PdfEntryRecord { 'id' : string; 'blockId' : string; 'filename' : string; 'base64Data' : string; 'uploadedAt' : bigint; }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'error' : string }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'error' : string }
  >,
  'incrementVisitorCount' : ActorMethod<[], undefined>,
  'recordHeartbeat' : ActorMethod<[string], undefined>,
  'getActiveVisitorCount' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'error' : string }
  >,
  'getMusterschreibenCount' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'error' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'error' : string }
  >,
  'register' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCryptoAddress' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'getCryptoAddresses' : ActorMethod<[], Array<CryptoAddress>>,
  'submitPaymentProof' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'getMyPaymentStatus' : ActorMethod<[string], [] | [PaymentRequestRecord]>,
  'getAllPaymentRequests' : ActorMethod<
    [string],
    { 'ok' : Array<PaymentRequestRecord> } |
      { 'error' : string }
  >,
  'approvePayment' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'rejectPayment' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'hasMusterschreibenAccess' : ActorMethod<[string], boolean>,
  'grantMusterschreibenAccess' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'revokeMusterschreibenAccess' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'verifyBTCTransaction' : ActorMethod<
    [string, string],
    { 'confirmed' : null } |
      { 'pending' : null } |
      { 'error' : string }
  >,
  'addPdfEntry' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'error' : string }
  >,
  'deletePdfEntry' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'error' : string }
  >,
  'getPdfEntriesByBlock' : ActorMethod<[string], Array<PdfEntryRecord>>,
  'getAllPdfEntries' : ActorMethod<
    [string],
    { 'ok' : Array<PdfEntryRecord> } |
      { 'error' : string }
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<[string], { 'method' : string; 'blob_hash' : string }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
